name: go lint, vet, test, build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: golangci
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.5

    - name: vet
      run: go vet ./...

    - name: test
      run: go test -v ./...

    - name: build
      run: go build ./...